name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Instala Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Instala dependencias
        run: npm install
      - name: Ejecuta pruebas
        run: npm test
