- hosts: all
  tasks:
    - name: Instalar Apache
      apt:
        name: apache2
        state: present
    - name: Copiar archivos HTML
      copy:
        src: index.html
        dest: /var/www/html/index.html
    - name: Iniciar Apache
      service:
        name: apache2
        state: started
